### ISSUE TITLE
[Question] Data standardization / scaling and inverse_transform on predicted series

### ISSUE THREAD

**Issue by carusyte** [Secilia-Cxy/SOFTS#7]
To be honest, I'm not a data scientist. Just curious: if standardization is applied on the inputs:

https://github.com/Secilia-Cxy/SOFTS/blob/011c805c4b040b0e6431ee3a2451348729bd87ae/run_on_your_own_dataset.ipynb#L171-L181

Would it be necessary or better off to perform `inverse_transformation` on the predictions?

https://github.com/Secilia-Cxy/SOFTS/blob/011c805c4b040b0e6431ee3a2451348729bd87ae/run_on_your_own_dataset.ipynb#L580-L582

E.g.
`scaler.inverse_transform(predictions)`

**Comment by Secilia-Cxy** [comment]
In practical applications, it is indeed possible to use inverse_transform on the predictions. However, the reason we do not use inverse_transform in this context is that when calculating the Mean Squared Error (MSE), applying the inverse transformation can cause the MSE of certain channels to be particularly large due to the inherently high values in those channels. This would not accurately reflect the model's average predictive performance across all channels. Therefore, we choose to compute MSE on the standardized data to better assess the overall predictive ability of the model.

**Comment by hanlu-nju** [comment]
> In practical applications, it is indeed possible to use inverse_transform on the predictions. However, the reason we do not use inverse_transform in this context is that when calculating the Mean Squared Error (MSE), applying the inverse transformation can cause the MSE of certain channels to be particularly large due to the inherently high values in those channels. This would not accurately reflect the model's average predictive performance across all channels. Therefore, we choose to compute MSE on the standardized data to better assess the overall predictive ability of the model.

This is a research convention to ensure a fair comparison among channels of different scales. See the [first paper](https://arxiv.org/pdf/2012.07436) to come up with the benchmark and [its code](https://arxiv.org/pdf/2012.07436).
